version: '3.7'
services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'