spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
  flyway:
    password: password
    url: jdbc:postgresql://localhost:5432/db
    user: postgres